// ─────────────────────────────────────────────────────────────
// PX03/PX04 – Demo data for exception operations & diagnostics
// Realistic exception data with various types and recovery states
// ─────────────────────────────────────────────────────────────

import type {
  ExceptionSignal,
  ExceptionSummary,
  AuditEntry,
  Org360,
  DiagnosticEntry,
} from "@/lib/types/operations-internal";

// ── Exception summary ───────────────────────────────────────

export const DEMO_EXCEPTION_SUMMARY: ExceptionSummary = {
  healthyTenants: 23,
  needingAction: 5,
  permissionFailures: 2,
  stalledSyncs: 1,
  deadLetters: 3,
  billingIssues: 1,
  webhookLags: 2,
  highCostTenants: 1,
};

// ── Exception signals ───────────────────────────────────────

export const DEMO_EXCEPTIONS: ExceptionSignal[] = [
  {
    id: "ex_perm_001",
    category: "permission_failure",
    severity: "critical",
    status: "open",
    orgId: "org_cgl",
    orgName: "Creator Growth Lab",
    title: "Whop OAuth token revoked",
    description: "Creator revoked RescueLoop's access token. All automated interventions halted.",
    occurredAt: "2025-03-04T09:12:00Z",
    lastSeenAt: "2025-03-04T09:12:00Z",
    count: 1,
    recoverable: false,
    recoveryStrategy: "flag_and_notify",
    metadata: { scope: "members:read,interventions:write", revokedBy: "creator" },
  },
  {
    id: "ex_perm_002",
    category: "permission_failure",
    severity: "high",
    status: "investigating",
    orgId: "org_dsm",
    orgName: "Design Skills Mastery",
    title: "Webhook endpoint permission denied",
    description: "Webhook delivery returns 403. Creator may have changed API key permissions.",
    occurredAt: "2025-03-04T08:30:00Z",
    lastSeenAt: "2025-03-04T10:45:00Z",
    count: 4,
    recoverable: true,
    recoveryStrategy: "flag_and_notify",
    metadata: { endpoint: "/api/webhooks/whop", httpStatus: "403" },
  },
  {
    id: "ex_sync_001",
    category: "stalled_sync",
    severity: "high",
    status: "recovering",
    orgId: "org_cca",
    orgName: "Course Creator Academy",
    title: "Member sync stalled — 2h behind",
    description: "Whop API returns 5xx on member list endpoint. Sync has not progressed since 07:00.",
    occurredAt: "2025-03-04T07:00:00Z",
    lastSeenAt: "2025-03-04T09:05:00Z",
    count: 12,
    recoverable: true,
    recoveryStrategy: "retry_with_jitter",
    metadata: { lagMs: "7200000", lastSuccessfulSync: "2025-03-04T07:00:00Z" },
  },
  {
    id: "ex_dl_001",
    category: "dead_letter",
    severity: "medium",
    status: "open",
    orgId: "org_cgl",
    orgName: "Creator Growth Lab",
    title: "3 intervention emails in dead letter queue",
    description: "Email delivery failed after 3 retries. Messages are queued in dead-letter for manual review.",
    occurredAt: "2025-03-04T06:22:00Z",
    lastSeenAt: "2025-03-04T08:15:00Z",
    count: 3,
    recoverable: true,
    recoveryStrategy: "retry_and_dead_letter",
    metadata: { queueSize: "3", oldestMessage: "2025-03-04T06:22:00Z" },
  },
  {
    id: "ex_dl_002",
    category: "dead_letter",
    severity: "low",
    status: "resolved",
    orgId: "org_dsm",
    orgName: "Design Skills Mastery",
    title: "Stale webhook event purged",
    description: "A webhook event older than 24h was automatically purged from the dead-letter queue.",
    occurredAt: "2025-03-03T14:00:00Z",
    lastSeenAt: "2025-03-04T02:00:00Z",
    count: 1,
    recoverable: false,
    metadata: { eventAge: "26h", eventType: "membership.updated" },
  },
  {
    id: "ex_dl_003",
    category: "dead_letter",
    severity: "medium",
    status: "open",
    orgId: "org_cca",
    orgName: "Course Creator Academy",
    title: "Duplicate webhook in dead letter",
    description: "A duplicate membership.created event failed dedup and landed in dead-letter.",
    occurredAt: "2025-03-04T11:05:00Z",
    lastSeenAt: "2025-03-04T11:05:00Z",
    count: 1,
    recoverable: true,
    recoveryStrategy: "retry_and_dead_letter",
    metadata: { eventId: "evt_dup_001", reason: "dedup_collision" },
  },
  {
    id: "ex_bill_001",
    category: "billing_issue",
    severity: "high",
    status: "open",
    orgId: "org_cgl",
    orgName: "Creator Growth Lab",
    title: "Whop billing webhook discrepancy",
    description: "Reported monthly spend ($347) exceeds plan limit ($299). Usage-based overage detected.",
    occurredAt: "2025-03-04T00:00:00Z",
    lastSeenAt: "2025-03-04T00:00:00Z",
    count: 1,
    recoverable: true,
    recoveryStrategy: "flag_and_notify",
    metadata: { reportedSpend: "$347", planLimit: "$299" },
  },
  {
    id: "ex_wh_001",
    category: "webhook_lag",
    severity: "medium",
    status: "recovering",
    orgId: "org_cgl",
    orgName: "Creator Growth Lab",
    title: "Webhook delivery lag: 45s average",
    description: "Whop webhook delivery is experiencing high latency. Average response time is 45s (threshold: 10s).",
    occurredAt: "2025-03-04T08:00:00Z",
    lastSeenAt: "2025-03-04T10:30:00Z",
    count: 28,
    recoverable: true,
    recoveryStrategy: "retry_with_jitter",
    metadata: { avgLatencyMs: "45000", thresholdMs: "10000", p99Ms: "72000" },
  },
  {
    id: "ex_wh_002",
    category: "webhook_lag",
    severity: "high",
    status: "escalated",
    orgId: "org_cca",
    orgName: "Course Creator Academy",
    title: "Webhook timeout — Whop endpoint unreachable",
    description: "All webhook deliveries timing out after 30s. Possible Whop-side outage.",
    occurredAt: "2025-03-04T09:40:00Z",
    lastSeenAt: "2025-03-04T10:50:00Z",
    count: 15,
    recoverable: true,
    recoveryStrategy: "retry_and_dead_letter",
    metadata: { timeoutMs: "30000", affectedEndpoints: "all" },
  },
  {
    id: "ex_cost_001",
    category: "high_cost_tenant",
    severity: "medium",
    status: "investigating",
    orgId: "org_cca",
    orgName: "Course Creator Academy",
    title: "Cost anomaly — 3x normal API usage",
    description: "Tenant's API usage spiked to 3x their 30-day average. May indicate a sync loop.",
    occurredAt: "2025-03-04T07:30:00Z",
    lastSeenAt: "2025-03-04T10:00:00Z",
    count: 1,
    recoverable: true,
    recoveryStrategy: "flag_and_notify",
    metadata: { normalAvgCalls: "420/day", currentCalls: "1260/day", period: "4h" },
  },
];

// ── Audit entries ───────────────────────────────────────────

export const DEMO_AUDIT_LOG: AuditEntry[] = [
  {
    id: "aud_001",
    timestamp: "2025-03-04T10:52:00Z",
    action: "retry_operation",
    actor: "system",
    targetOrgId: "org_cca",
    targetResourceId: "ex_sync_001",
    result: "success",
    details: "Retried Whop member sync — 5xx resolved, sync resumed",
    idempotencyKey: "retry:ex_sync_001:1709554320",
  },
  {
    id: "aud_002",
    timestamp: "2025-03-04T10:30:00Z",
    action: "escalate",
    actor: "operator@rescueloop.dev",
    targetOrgId: "org_cca",
    targetResourceId: "ex_wh_002",
    result: "success",
    details: "Escalated webhook timeout to Whop support — ticket #WH-4521",
    idempotencyKey: "escalate:ex_wh_002:1709553000",
  },
  {
    id: "aud_003",
    timestamp: "2025-03-04T09:45:00Z",
    action: "force_sync",
    actor: "operator@rescueloop.dev",
    targetOrgId: "org_cca",
    targetResourceId: "sync_member_list",
    result: "failed",
    details: "Force sync failed — Whop API returned 503",
    idempotencyKey: "force_sync:org_cca:1709551500",
  },
  {
    id: "aud_004",
    timestamp: "2025-03-04T09:15:00Z",
    action: "flag_high_cost",
    actor: "system",
    targetOrgId: "org_cca",
    targetResourceId: "ex_cost_001",
    result: "success",
    details: "Flagged cost anomaly — API usage 3x above average",
    idempotencyKey: "flag:ex_cost_001:1709550900",
  },
  {
    id: "aud_005",
    timestamp: "2025-03-04T09:12:00Z",
    action: "revoke_permission",
    actor: "creator@cgl.dev",
    targetOrgId: "org_cgl",
    targetResourceId: "whop_oauth_token",
    result: "success",
    details: "Creator revoked OAuth token — interventions halted",
    idempotencyKey: "revoke:whop_oauth:1709550720",
  },
  {
    id: "aud_006",
    timestamp: "2025-03-04T08:00:00Z",
    action: "run_diagnostics",
    actor: "operator@rescueloop.dev",
    targetOrgId: "org_cgl",
    targetResourceId: "ex_wh_001",
    result: "success",
    details: "Ran diagnostics on webhook lag — identified slow downstream endpoint",
    idempotencyKey: "diag:ex_wh_001:1709546400",
  },
  {
    id: "aud_007",
    timestamp: "2025-03-04T06:30:00Z",
    action: "purge_dead_letter",
    actor: "system",
    targetOrgId: "org_dsm",
    targetResourceId: "ex_dl_002",
    result: "success",
    details: "Auto-purged dead-letter event older than 24h",
    idempotencyKey: "purge:ex_dl_002:1709537400",
  },
  {
    id: "aud_008",
    timestamp: "2025-03-04T06:22:00Z",
    action: "resend_webhook",
    actor: "system",
    targetOrgId: "org_cgl",
    targetResourceId: "ex_dl_001",
    result: "failed",
    details: "Webhook resend attempt 3/3 failed — moved to dead letter",
    idempotencyKey: "resend:ex_dl_001:1709536920",
  },
];

// ── Org 360 views ───────────────────────────────────────────

export const DEMO_ORG_360: Org360[] = [
  {
    orgId: "org_cgl",
    orgName: "Creator Growth Lab",
    healthStatus: "critical",
    memberCount: 742,
    activeInterventions: 18,
    recoveryRate: 0.72,
    monthlySpend: 347,
    signals: DEMO_EXCEPTIONS.filter((e) => e.orgId === "org_cgl"),
    recentEvents: DEMO_AUDIT_LOG.filter((a) => a.targetOrgId === "org_cgl"),
  },
  {
    orgId: "org_dsm",
    orgName: "Design Skills Mastery",
    healthStatus: "degraded",
    memberCount: 412,
    activeInterventions: 7,
    recoveryRate: 0.85,
    monthlySpend: 199,
    signals: DEMO_EXCEPTIONS.filter((e) => e.orgId === "org_dsm"),
    recentEvents: DEMO_AUDIT_LOG.filter((a) => a.targetOrgId === "org_dsm"),
  },
  {
    orgId: "org_cca",
    orgName: "Course Creator Academy",
    healthStatus: "critical",
    memberCount: 588,
    activeInterventions: 24,
    recoveryRate: 0.64,
    monthlySpend: 299,
    signals: DEMO_EXCEPTIONS.filter((e) => e.orgId === "org_cca"),
    recentEvents: DEMO_AUDIT_LOG.filter((a) => a.targetOrgId === "org_cca"),
  },
];

// ── Diagnostics entries ─────────────────────────────────────

export const DEMO_DIAGNOSTICS: DiagnosticEntry[] = [
  {
    id: "diag_001",
    errorId: "ERR-WHOP-429-org_cgl",
    timestamp: "2025-03-04T10:55:00Z",
    severity: "warning",
    category: "stalled_sync",
    title: "Whop API rate limit hit during member sync",
    description: "Received HTTP 429 while syncing member list for Creator Growth Lab. Backoff strategy engaged.",
    context: { orgId: "org_cgl", endpoint: "/v1/members", httpStatus: "429", rateLimitRemaining: "0" },
    recoverySuggestion: "Wait for rate limit window to reset (60s). The exponential backoff strategy will automatically retry.",
    recoveryRule: {
      failureType: "whop_api_429",
      recoveryAction: "exponential_backoff",
      maxRetries: 8,
      baseDelayMs: 1_000,
      maxDelayMs: 120_000,
      description: "Exponential backoff for Whop API 429",
    },
    recoveryStatus: "in_progress",
    retryCount: 3,
    maxRetries: 8,
    lastRetryAt: "2025-03-04T10:52:00Z",
    nextRetryAt: "2025-03-04T10:56:00Z",
  },
  {
    id: "diag_002",
    errorId: "ERR-WHOP-5xx-org_cca",
    timestamp: "2025-03-04T09:40:00Z",
    severity: "error",
    category: "stalled_sync",
    title: "Whop API server error on member endpoint",
    description: "Whop API returned 503 for member list. Retry with jitter strategy engaged.",
    context: { orgId: "org_cca", endpoint: "/v1/members", httpStatus: "503", upstream: "whop-api" },
    recoverySuggestion: "The Whop API is experiencing issues. Retries with jitter will continue. If this persists for >30 min, check status.whop.com.",
    recoveryRule: {
      failureType: "whop_api_5xx",
      recoveryAction: "retry_with_jitter",
      maxRetries: 5,
      baseDelayMs: 2_000,
      maxDelayMs: 60_000,
      description: "Retry with jitter for Whop API 5xx",
    },
    recoveryStatus: "in_progress",
    retryCount: 2,
    maxRetries: 5,
    lastRetryAt: "2025-03-04T09:50:00Z",
    nextRetryAt: "2025-03-04T09:57:00Z",
  },
  {
    id: "diag_003",
    errorId: "ERR-WH-timeout-org_cca",
    timestamp: "2025-03-04T09:40:00Z",
    severity: "critical",
    category: "webhook_lag",
    title: "Webhook delivery timeout",
    description: "All webhook deliveries timing out after 30s. Events are being queued in dead-letter after 3 retries.",
    context: { orgId: "org_cca", timeoutMs: "30000", eventType: "membership.updated", retryAttempt: "3" },
    recoverySuggestion: "Escalated to Whop support (ticket #WH-4521). Dead-letter events can be manually replayed once Whop resolves the issue.",
    recoveryRule: {
      failureType: "webhook_timeout",
      recoveryAction: "retry_and_dead_letter",
      maxRetries: 3,
      baseDelayMs: 5_000,
      maxDelayMs: 30_000,
      description: "Retry + dead letter for webhook timeout",
    },
    recoveryStatus: "max_retries_exceeded",
    retryCount: 3,
    maxRetries: 3,
    lastRetryAt: "2025-03-04T10:20:00Z",
    nextRetryAt: null,
  },
  {
    id: "diag_004",
    errorId: "ERR-DB-conn",
    timestamp: "2025-03-04T04:12:00Z",
    severity: "warning",
    category: "system",
    title: "Database connection pool exhausted",
    description: "Connection pool reached max connections. Some queries queued until connections freed.",
    context: { poolSize: "20", activeConnections: "20", waitingQueries: "3" },
    recoverySuggestion: "The pool recovered after a brief spike. Consider increasing pool size if this recurs frequently.",
    recoveryRule: {
      failureType: "db_connection_error",
      recoveryAction: "reconnect_and_retry",
      maxRetries: 4,
      baseDelayMs: 500,
      maxDelayMs: 10_000,
      description: "Reconnect + retry for DB connection error",
    },
    recoveryStatus: "succeeded",
    retryCount: 1,
    maxRetries: 4,
    lastRetryAt: "2025-03-04T04:12:30Z",
    nextRetryAt: null,
  },
  {
    id: "diag_005",
    errorId: "ERR-PERM-revoked-org_cgl",
    timestamp: "2025-03-04T09:12:00Z",
    severity: "critical",
    category: "permission_failure",
    title: "OAuth permission revoked by creator",
    description: "Creator Growth Lab's creator revoked RescueLoop's OAuth token. All automated operations halted.",
    context: { orgId: "org_cgl", scope: "members:read,interventions:write", revokedBy: "creator" },
    recoverySuggestion: "The creator must re-authorize RescueLoop via the Whop OAuth flow. A notification has been sent. No automatic retry is possible.",
    recoveryRule: {
      failureType: "permission_revoked",
      recoveryAction: "flag_and_notify",
      maxRetries: 0,
      baseDelayMs: 0,
      maxDelayMs: 0,
      description: "Flag & notify for permission revoked",
    },
    recoveryStatus: "failed",
    retryCount: 0,
    maxRetries: 0,
    lastRetryAt: null,
    nextRetryAt: null,
  },
  {
    id: "diag_006",
    errorId: "ERR-COST-org_cca",
    timestamp: "2025-03-04T07:30:00Z",
    severity: "warning",
    category: "high_cost_tenant",
    title: "Cost anomaly detected",
    description: "Course Creator Academy's API usage is 3x their 30-day average. Possible sync loop.",
    context: { orgId: "org_cca", normalAvgCalls: "420/day", currentCalls: "1260/day" },
    recoverySuggestion: "Investigate whether a sync loop is causing excess API calls. Consider pausing automated sync for this tenant until root cause is identified.",
    recoveryStatus: "none",
    retryCount: 0,
    maxRetries: 0,
    lastRetryAt: null,
    nextRetryAt: null,
  },
  {
    id: "diag_007",
    errorId: "ERR-BILL-org_cgl",
    timestamp: "2025-03-04T00:00:00Z",
    severity: "error",
    category: "billing_issue",
    title: "Billing overage detected",
    description: "Creator Growth Lab's monthly spend ($347) exceeds plan limit ($299).",
    context: { orgId: "org_cgl", reportedSpend: "$347", planLimit: "$299", overage: "$48" },
    recoverySuggestion: "Review usage breakdown. If overage is from a sync loop, address that first. Otherwise, discuss plan upgrade with the tenant.",
    recoveryStatus: "none",
    retryCount: 0,
    maxRetries: 0,
    lastRetryAt: null,
    nextRetryAt: null,
  },
];
